#pragma once

#include <unity.h>

#include <k2o/order.hpp>

void order_DO_serialize_argument_into_stream_EXPECT_order_getting_unaltered_argument();
void order_DO_give_then_return_argument_from_order_EXPECT_unaltered_value();
void order_DO_instantiate_order_with_functor_taking_arguments_EXPECT_input_and_output_sizes_correct();
void order_DO_instantiate_order_with_functor_taking_no_arguments_EXPECT_input_and_output_sizes_correct();
void order_DO_instantiate_order_with_functor_returning_non_tuple_EXPECT_input_and_output_sizes_correct();
void order_DO_instantiate_order_with_functor_non_returning_EXPECT_input_and_output_sizes_correct();
