cmake_minimum_required(VERSION 3.10)

include(UpdParseCliArguments)

upd_parse_cli_arguments(
  KEYWORDS
  "SOURCE_FILE"
  "DRY_RUN"
  "INCLUDE_DIRECTORIES"
  "INTERFACE_INCLUDE_DIRECTORIES"
  "COMPILE_DEFINITIONS"
  "INTERFACE_COMPILE_DEFINITIONS"
  "COMPILE_FEATURES"
  "INTERFACE_COMPILE_FEATURES"
  "COMPILE_OPTIONS"
  "INTERFACE_COMPILE_OPTIONS"
  "CMAKE_BINARY_DIR"
  OPTIONS
  "PRIVATE_SOURCE")

find_program(CLANG_FORMAT_COMMAND clang-format
  DOC "Check and/or fix C/C++ source format" REQUIRED)

set(FLAGS)

if(DRY_RUN)
  list(APPEND FLAGS --dry-run -Werror)
else()
  list(APPEND FLAGS -i)
endif()

execute_process(COMMAND ${CLANG_FORMAT_COMMAND} ${SOURCE_FILE} ${FLAGS})
