cmake_minimum_required(VERSION 3.10)

include(UpdParseCliArguments)

upd_parse_cli_arguments(
  KEYWORDS
  "SOURCE_FILE"
  "INCLUDE_DIRECTORIES"
  "INTERFACE_INCLUDE_DIRECTORIES"
  "COMPILE_DEFINITIONS"
  "INTERFACE_COMPILE_DEFINITIONS"
  "COMPILE_FEATURES"
  "INTERFACE_COMPILE_FEATURES"
  "INTERFACE_COMPILE_OPTIONS"
  "CMAKE_BINARY_DIR"
  OPTIONS
  "IS_SOURCE")

find_program(CLANG_TIDY_COMMAND clang-tidy
  DOC "Static analyzer for C and C++ code" REQUIRED)

execute_process(
  COMMAND ${CLANG_TIDY_COMMAND} ${SOURCE_FILE} -p ${CMAKE_BINARY_DIR}/compile_commands.json --use-color
  COMMAND_ERROR_IS_FATAL ANY)
