name: "Prepare Environment"
description: "Build and upload development container"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/cache@v5
      with:
        path: |
          build_gcc
          build_clang
          .ccache
        key: ${{ runner.os }}-${{ github.job }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ github.job }} 
    - uses: docker/setup-compose-action@v2
      with:
        version: latest
    - uses: actions/download-artifact@v4
      with:
        name: devcontainer
    - run: docker load --input devcontainer.tar
      shell: bash
    - run: ln --symbolic .github/devcontainer/docker-compose.yml docker-compose.yml
      shell: bash
    - run: sudo apt install --assume-yes git-restore-mtime
      shell: bash
    - run: git config set --global alias.whatchanged 'log --raw --no-merges'
      shell: bash
    - run: git restore-mtime
      shell: bash
    - run: find -printf "%Tc %p\n" || true
      shell: bash
