runs:
  using: composite
  steps:
    - uses: actions/cache@v5
      with:
        path: build_gcc
        key: ${{ runner.os }}-${{ github.job }}
    - uses: docker/setup-compose-action@v2
      with:
        version: latest
    - uses: actions/download-artifact@v4
      with:
        name: devcontainer
    - run: docker load --input devcontainer.tar
      shell: bash
    - run: ln --symbolic .github/devcontainer/docker-compose.yml docker-compose.yml
      shell: bash
