#!/bin/sh

GIT_TOP_LEVEL=$(git rev-parse --show-toplevel)

cd $GIT_TOP_LEVEL
cmake -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DEXECUTABLE_OUTPUT_PATH=bin
cmake --build build
cd build && ctest --rerun-failed --output-on-failure
