services:
  base:
    image: devcontainer
    user: "${UID}:${GID}"
    volumes:
      - .:/home/alpine/Unpadded
    working_dir: /home/alpine/Unpadded
    tty: true
    environment:
      VERBOSE: "1"
      CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
      CCACHE_DIR: "/home/alpine/Unpadded/.ccache"
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: "6"
      CCACHE_MAXSIZE: "1G"

  configure_clang:
    extends: base
    command: cmake --preset clang

  check_full_clang:
    extends: base
    command: cmake --build build_clang --target check_full --parallel

  configure_gcc:
    extends: base
    command: cmake --preset gcc

  report_build_time:
    extends: base
    command: bash -c 'ClangBuildAnalyzer --all build_clang capture.bin && ClangBuildAnalyzer --analyze capture.bin'
  
  check_full_gcc:
    extends: base
    command: cmake --build build_gcc --target check_full --parallel

  print_ccache_stats:
    extends: base
    command: ccache --print-stats && ccache --show-stats

  format:
    extends: base
    command: cmake --build build_clang --target clang_format --parallel

  iwyu:
    extends: base
    command: cmake --build build_clang --target iwyu --parallel

  lint:
    extends: base
    command: cmake --build build_clang --target clang_tidy --parallel
