name: C/C++ CI

on:
  push:
    branches:
        - master
        - template_optimization
  pull_request:
    branches:
      - master
      - template_optimization

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ./configure
      run: ./configure
    - name: make check
      run: make check
