name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir obj
      run: mkdir obj
    - name: git submodule update --init --recursive
      run: git submodule update --init --recursive
    - name: make check
      run: make check
