name: check-with-clang
run-name: Build and run all tests with Clang
on:
  workflow_run:
    workflows: ["build-devcontainer"]
    types:
      - completed

jobs:
  check-with-clang:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: build
          key: ${{ runner.os }}-check-with-clang
      - uses: actions/download-artifact@v8
        with:
          name: devcontainer
      - run: docker load --input devcontainer.tar
      - run: docker run devcontainer cmake --preset clang
      - run: |
          docker run devcontainer cmake \
          --build build_clang \
          --target check_full \
          --parallel $(nproc)
