name: Build and run all tests with Clang
on:
  push:
    branches:
      - unstable-v2
jobs:
  check-with-clang:
    runs-on: ubuntu-latest
    needs: build-devcontainer
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: build
          key: ${{ runner.os }}-check-with-clang
      - uses: actions/download-artifact@v8
        with:
          name: devcontainer
      - run: docker load --input devcontainer.tar
      - run: docker run devcontainer cmake --preset clang
      - run: |
          docker run devcontainer cmake \
          --build build_clang \
          --target check_full \
          --parallel $(nproc)
