name: CI/CD pipeline
on:
  push:
    branches:
      - unstable-v2
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ github.workspace }}/build_clang
          key: ${{ runner.os }}-build
      - uses: ./.github/install
        with:
          entrypoint: /entrypoint.sh
