name: CI/CD pipeline
on:
  push:
    branches:
      - unstable-v2
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            /home/ubuntu/build
            /home/ubuntu/build_clang
          key: build-${{ steps.date.outputs.date }}
          restore-keys: build
      - uses: ./.github/install
        with:
          entrypoint: /entrypoint.sh
