name: Pip Installation Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install ccache gcc-11
    - run: python3.10 -m venv venv
    - run: venv/bin/pip install . pytest pytest-asyncio 
    - run: CC="gcc-11" CXX="g++-11" venv/bin/python -m pytest test/py/test.py
